{
    "name": "Rental",
    "version": "0.0.1",
    "private": true,
    "scripts": {
      "android": "react-native run-android",
      "ios": "react-native run-ios",
      "start": "react-native start",
      "test": "jest",
      "lint": "eslint ."
    },
    "dependencies": {
      "@react-native-community/blur": "^3.6.0",
      "@react-native-community/checkbox": "^0.5.8",
      "@react-native-community/cookies": "^5.0.1",
      "@react-native-community/datetimepicker": "^3.5.2",
      "@react-native-firebase/app": "^14.5.1",
      "@react-native-firebase/auth": "^14.5.1",
      "@react-native-firebase/messaging": "^14.5.1",
      "@react-native-google-signin/google-signin": "^7.0.4",
      "@react-native-masked-view/masked-view": "^0.2.6",
      "geolib": "^3.3.1",
      "icons": "^1.0.0",
      "moment": "^2.29.1",
      "native": "^0.3.3",
      "native-base": "^2.15.2",
      "react": "^17.0.1",
      "react-native": "0.64.2",
      "react-native-app-intro-slider": "^4.0.4",
      "react-native-circle-checkbox": "^0.1.6",
      "react-native-confirmation-code-field": "^7.3.0",
      "react-native-country-picker-modal": "^2.0.0",
      "react-native-credit-card-input": "^0.4.1",
      "react-native-datepicker": "^1.7.2",
      "react-native-drawer": "^2.5.1",
      "react-native-fbsdk": "^3.0.0",
      "react-native-gesture-handler": "^1.10.3",
      "react-native-get-location": "^2.2.1",
      "react-native-image-crop-picker": "^0.37.3",
      "react-native-image-picker": "^4.7.3",
      "react-native-image-placeholder": "^1.0.14",
      "react-native-image-resizer": "^1.4.5",
      "react-native-image-slider-box": "^1.1.20",
      "react-native-image-zoom-viewer": "^3.0.1",
      "react-native-img-placeholder": "^1.0.0",
      "react-native-incall-manager": "^3.3.0",
      "react-native-indicators": "^0.17.0",
      "react-native-instagram-login": "^2.0.5",
      "react-native-linear-gradient": "^2.5.6",
      "react-native-loading-spinner-overlay": "^2.0.0",
      "react-native-maps": "^0.30.1",
      "react-native-modal-datetime-picker": "^13.0.1",
      "react-native-normalize": "^1.0.1",
      "react-native-openanything": "^0.0.6",
      "react-native-paypal": "^4.1.0",
      "react-native-popup-dialog": "^0.18.3",
      "react-native-progress": "^5.0.0",
      "react-native-push-notification": "^8.1.1",
      "react-native-ratings": "^8.1.0",
      "react-native-raw-bottom-sheet": "^2.2.0",
      "react-native-reanimated": "^1.13.3",
      "react-native-responsive-screen": "^1.4.2",
      "react-native-router-flux": "^4.3.1",
      "react-native-safe-area-context": "^3.2.0",
      "react-native-screens": "^3.4.0",
      "react-native-simple-radio-button": "^2.7.4",
      "react-native-skeleton-placeholder": "^5.0.0",
      "react-native-star-rating": "^1.1.0",
      "react-native-stopwatch-timer": "^0.0.21",
      "react-native-stripe-api": "^0.1.0",
      "react-native-swiper": "^1.6.0",
      "react-native-switch-audio-output": "^1.1.2",
      "react-native-system-setting": "^1.7.6",
      "react-native-twilio-video-webrtc": "^2.1.0",
      "react-native-vector-icons": "^8.1.0",
      "react-native-webview": "^11.17.1",
      "react-redux": "^7.2.5",
      "redux": "^4.1.1",
      "vector": "^0.0.4"
    },
    "devDependencies": {
      "@babel/core": "7.14.8",
      "@babel/runtime": "7.14.8",
      "@react-native-community/eslint-config": "2.0.0",
      "babel-jest": "26.6.3",
      "eslint": "7.14.0",
      "jest": "26.6.3",
      "metro-react-native-babel-preset": "0.64.0",
      "react-test-renderer": "17.0.1"
    },
    "jest": {
      "preset": "react-native"
    }
  }